lesson_1/geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = "adminapp"

urlpatterns = [
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UsersDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),

]

lesson_1/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>', authapp.verify, name='verify'),
]

lesson_1/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', contacts, name="contacts"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="auth")),
    path('basket/', include('basketapp.urls', namespace="basket")),
    path('orders/', include('ordersapp.urls', namespace="orders")),
    path('admin_staff/', include('adminapp.urls', namespace="admin_staff")),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

lesson_1/geekshop/adminapp/models.py
from django.db import models

# Create your models here.

lesson_1/geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'is_active':
                field.widget.attrs['class'] = ''
            field.help_text = ''


class ProductCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'is_active':
                field.widget.attrs['class'] = ''
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'is_active':
                field.widget.attrs['class'] = ''
            field.help_text = ''

class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'is_active':
                field.widget.attrs['class'] = ''
            field.help_text = ''

lesson_1/geekshop/adminapp/views.py
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.db import connection
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, reverse
from django.urls import reverse_lazy

from adminapp.forms import ProductCategoryCreateForm, ProductCategoryEditForm, ProductEditForm, ProductCreateForm
from authapp.forms import ShopUserRegisterForm, ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from django.contrib.auth.decorators import user_passes_test
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin


class UsersListView(LoginRequiredMixin,ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    login_url = '/'

    def get_context_data(self,*,object_list=None,**kwargs):
        context = super(UsersListView, self).get_context_data()
        context['title'] = 'админка/пользователи'
        return context

    # def get(self,request,*args,**kwargs):
    #     get_con = super(UsersListView, self).get()
    #     return get_con
# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка/пользователи'
#
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#
#     context = {
#         'title': title,
#         'objects': users_list
#     }
#
#     return render(request, 'adminapp/users.html', context)

class UsersCreateView(CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')

# def user_create(request):
#     title = 'пользователи/создания'
#
#     if request.method == 'POST':
#         user_form = ShopUserRegisterForm(request.POST, request.FILES)
#         if user_form.is_valid():
#             user_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:users'))
#     else:
#         user_form = ShopUserRegisterForm()
#     context = {
#         'title': title,
#         'user_form': user_form
#     }
#
#     return render(request, 'adminapp/user_update.html', context)

class UsersUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserRegisterForm # CBV 
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')


# def user_update(request, pk):
#     title = 'пользователи/редактирование'
#
#     edit_user = get_object_or_404(ShopUser, pk=pk)
#
#
#
#     if request.method == 'POST':
#         edit_form = ShopUserEditForm(request.POST, request.FILES, instance=edit_user )
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('admin_staff:user_update', args=[edit_user.pk]))
#     else:
#         edit_form = ShopUserEditForm(instance=edit_user)
#
#
#     context = {
#         'title': title,
#         'update_form': edit_form
#     }
#
#     return render(request, 'adminapp/user_update.html', context)

class UsersDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin_staff:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())
    # def user_delete(request, pk):
#     title = 'пользователи/удаление'
#
#     user = get_object_or_404(ShopUser, pk=pk)
#
#     if request.method == 'POST':
#         user.is_active = False
#         user.save()
#         return HttpResponseRedirect(reverse('admin_staff:users'))
#
#
#     context = {
#         'title': title,
#         'user_to_delete': user
#     }
#
#     return render(request, 'adminapp/user_delete.html', context)


def categories(request):
    title = 'админка/категории'

    categories_list = ProductCategory.objects.all()

    content = {
        'title': title,
        'objects': categories_list
    }

    return render(request, 'adminapp/categories.html', content)


def category_create(request):
    title = 'категории/создания'


    if request.method == 'POST':
        category_form = ProductCategoryCreateForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('admin_staff:categories'))

    else:
        category_form = ProductCategoryCreateForm()
    context = {
        'title': title,
        'category_form': category_form
    }

    return render(request, 'adminapp/category_update.html', context)

def category_update(request, pk):
    title = 'категории/редактирование'

    category_edit = get_object_or_404(ProductCategory,pk=pk)

    if request.method == 'POST':
        category_form = ProductCategoryEditForm(request.POST, request.FILES, instance=category_edit)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('admin_staff:category_update',args= [category_edit.pk]))

    else:
        category_form = ProductCategoryEditForm(instance=category_edit)
    context = {
        'title': title,
        'category_form': category_form
    }

    return render(request, 'adminapp/category_update.html', context)

def category_delete(request, pk):
    title = 'категории/удаление'

    category_del = get_object_or_404(ProductCategory,pk=pk)

    if request.method == 'POST':
        category_del.is_active = False
        category_del.save()
        return HttpResponseRedirect(reverse('admin_staff:categories'))


    context = {
        'title':title,
        'category_del':category_del,
    }
    return render(request,'adminapp/category_delete.html', context)


def products(request, pk=None):
    title = 'админка/продукт'

    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by('name')

    context = {
        'title': title,
        'category': category,
        'objects': products_list,
    }

    return render(request, 'adminapp/products.html', context)


def product_create(request, pk):
    title = 'продукт/создания'

    if request.method == 'POST':
        product_form = ProductCreateForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin_staff:products' ,args=[pk]))

    else:
        product_form = ProductCreateForm()
    context = {
        'title': title,
        'product_form': product_form
    }

    return render(request, 'adminapp/product_update.html', context)

def product_read(request, pk):
    title = 'продукт/чтение'

    product = get_object_or_404(Product, pk=pk)
    context = {'title': title, 'object': product }

    return render(request, 'adminapp/product_read.html', context)



def product_update(request, pk):
    title = 'продукт/редактирование'

    product_edit = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES, instance=product_edit)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin_staff:product_update', args=[product_edit.pk]))

    else:
        product_form = ProductEditForm(instance=product_edit)
    context = {
        'title': title,
        'product_form': product_form,
    }

    return render(request, 'adminapp/product_update.html', context)

def product_delete(request, pk):
    title = 'продукт/удаление'

    product_del = get_object_or_404(Product,pk=pk)

    if request.method == 'POST':
        product_del.is_active = False
        product_del.save()
        return HttpResponseRedirect(reverse('admin_staff:products', args=[product_del.category_id]))


    context = {
        'title':title,
        'product_del':product_del,
    }
    return render(request,'adminapp/product_delete.html', context)

def db_profile_by_type(prefix,type, queries):
    update_queries = list(filter(lambda x: type in x['sql'],queries))
    print(f'db_profile {type} for {prefix}: ')
    [print(query['sql']) for query in update_queries]

@receiver(pre_save, sender=ProductCategory)
def product_is_active_updated_productcategory_save(sender,instance,**kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)

        db_profile_by_type(sender,'UPDATE',connection.queries)

lesson_1/geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/style.css' %}">
        <link rel="stylesheet" type="text/css"href='https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css'>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">

    {% block css %}
    {% endblock %}

    <script src='{% static "adminapp/js/script.js" %}'></script>

    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'main' %}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'></i>
                <span class="nav_logo-name">Admin`ka</span>
            </a>
            {% include 'adminapp/inludes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Выход</span> </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

lesson_1/geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Категории
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Категория</th>
                                <th>Описание</th>
                                <th>Товары</th>
                                <th>Дата создания</th>
                                <th>Дата обновления</th>
                                <th>Активность</th>
                                <th>Удалить</th>

                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Категория</th>
                                <th>Описание</th>
                                <th>Товары</th>
                                <th>Дата создания</th>
                                <th>Дата обновления</th>
                                <th>Активность</th>
                                <th>Удалить</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for category in objects %}
                                <tr {% if not category.is_active %} style="opacity: 0.5;" {% endif %}>
                                    <td><a href="{% url 'admin_staff:category_update' category.pk %}"
                                           style="color: dodgerblue">{{ category.name }}</a></td>
                                    <td>{{ category.description }}</td>
                                    <td><a href="{% url 'admin_staff:products' category.pk %}"> product</a></td>

                                    <td>{{ category.created }}</td>
                                    <td>{{ category.updated }}</td>
                                    <td class="text-center">
                                        {% if category.is_active %}
                                            <i class="fa fa-check-circle"></i>
                                        {% else %}
                                            <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a {% if not category.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:category_delete' pk=category.pk %}">
                                            <i class="fa fa-times-circle"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admin_staff:category_create' %}">
                        <button class="btn btn-success">Создать Категории</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
     <div class="user_delete">
    Уверены, что хотите удалить {{ category_del.name }}?
    <form action="{% url 'admin_staff:category_delete' category_del.pk %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:categories' %}">
        Отмена
      </a>
    </button>
  </div>

{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post",enctype="multipart/form-data">
    {% csrf_token %}
    {{ category_form }}

  <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
     <div class="user_delete">
    Уверены, что хотите удалить {{ product_del.name }}?
    <form action="{% url 'admin_staff:product_delete' product_del.pk %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:products' product_del.category_id %}">
        Отмена
      </a>
    </button>
  </div>

{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
  <div class="product_read">
    <div class="product_name">
        Продукт<strong>{{ object.category.name|title }} /
                     {{ object.name|title }}</strong>
    </div>
    <img src="{{ object.image|media_folder_products }}"
         alt="{{ object.name }}">
    <div class="summary">
      <b>цена</b>
      <p>{{ object.price }} руб</p>
      <b>количество</b>
      <p>{{ object.quantity }}</p>
      <b>в каталоге</b>
      <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
      <p>
        <button>
          <a href={% url 'admin_staff:product_update' object.pk %}>
            редактировать
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'admin_staff:product_delete' object.pk %}>
            удалить
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'admin_staff:products' object.category.pk %}>
            назад
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>краткая информация</b>
      <p>{{ object.short_desc }}</p>
      <br><br>
      <b>подробная информация</b>
      <p>{{ object.description }}</p>
    </div>
  </div>
{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post",enctype="multipart/form-data">
    {% csrf_token %}
    {{ product_form }}

  <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Продукты</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Продукты
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Наменование</th>
                                <th>Детали</th>
                                <th>Редактирования</th>
                                <th>Активность</th>
                                <th>Удалить</th>

                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Наменование</th>
                                <th>Детали</th>
                                <th>Редактирования</th>
                                <th>Активность</th>
                                <th>Удалить</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for product in objects %}
                                <tr {% if not product.is_active %} style="opacity: 0.5;" {% endif %}>
                                    <td>{{ product.name }}</td>
                                    <td><a href="{% url 'admin_staff:product_read' product.pk%}"> Details</a></td>
                                    <td><a href="{% url 'admin_staff:product_update' product.pk%}"> Update</a></td>
                                    <td class="text-center">
                                        {% if product.is_active %}
                                            <i class="fa fa-check-circle"></i>
                                        {% else %}
                                            <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a {% if not product.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:product_delete' pk=product.pk %}">
                                            <i class="fa fa-times-circle"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">

                    <a href="{% url 'admin_staff:product_create' category.pk %}" >
                        <button class="btn btn-success">Создать Продукт</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
     <div class="user_delete">
    Уверены, что хотите удалить {{ object.username }}
    {% if object.first_name %}
      <b>({{ object.first_name|title }}</b>
      {% if object.last_name %}
        {{ object.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin_staff:user_delete' object.pk %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin_staff:users' %}">
        Отмена
      </a>
    </button>
  </div>

{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post",enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}

  <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

lesson_1/geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Пользователи
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Фамилия</th>
                            <th>Адрес эл. почты</th>
                            <th>Персонал сайта</th>
                            <th>Активный</th>
                            <th>Вход</th>
                            <th>Удалить</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in object_list %}
                            <tr {% if not user.is_active %} style="opacity: 0.5;" {% endif %}>
                                <td><a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td>{{ user.last_login }}</td>
                                <td>
                                    <a {% if not user.is_active %} class="invisible" {% endif %} href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                        <i class="fa fa-times-circle"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}