lesson_1/geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = "adminapp"

urlpatterns = [
    path('users/create/', adminapp.UsersCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UsersUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UsersDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),

]

lesson_1/geekshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>', authapp.verify, name='verify'),
]

lesson_1/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import main, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', contacts, name="contacts"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="auth")),
    path('basket/', include('basketapp.urls', namespace="basket")),
    path('orders/', include('ordersapp.urls', namespace="orders")),
    path('admin_staff/', include('adminapp.urls', namespace="admin_staff")),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

lesson_1/geekshop/ordersapp/urls.py
from django.urls import path

import ordersapp.views as ordersapp
app_name = "ordersapp"
urlpatterns = [
    path("",  ordersapp.OrderList.as_view(), name="main"),
    path('forming/complete/<int:pk>/',ordersapp.order_forming_complete, name='order_forming_complete'),
    path('create/', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<int:pk>/', ordersapp.OrderRead.as_view(), name='order_read'),
    path(r'update/<int:pk>/', ordersapp.OrderItemUpdate.as_view(),name='order_update'),
    path(r'delete/<int:pk>/', ordersapp.OrderDelete.as_view(), name='order_delete'),
    path(r'product/<int:pk>/price', ordersapp.get_product_price,  name='order_delete'),
]

lesson_1/geekshop/geekshop/views.py
from django.shortcuts import render

from basketapp.models import Basket
from mainapp.models import Product, Telefon


def main(request):
    title = "Магазин"



    products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')[:2]
    context = {
        'title': title,
        "products": products,
    }
    return render(request, "geekshop/index.html", context=context)


def contacts(request):
    title = "Контакты"


    telefon = Telefon.objects.all()[:5]
    context = {
        'title': title,
        'telefon': telefon,
    }
    return render(request, 'geekshop/contact.html', context=context)

lesson_1/geekshop/geekshop/templates/geekshop/includes/menu.html
<ul class="menu">
    <li><a href="{% url 'main' %}" class="{% if request.resolver_match.view_name == 'main' %}
    active {% endif %}">домой</a></li>
    <li><a href="{% url 'products:main' %}"
           class="{% if request.resolver_match.view_name == 'products:main' %} active {% endif %}">продукты</a></li>
    <li><a href="{% url 'contacts' %}" class="{% if request.resolver_match.view_name == 'contacts' %}
    active {% endif %}">контакты</a></li>
    {% if user.is_authenticated %}
        <li class=" dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"><a>
            {{ user.first_name|default:'Пользователь' }} </a>
        </li>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">


            <li>
                <a href="{% url 'auth:edit' %}" class="dropdown-item">
                    Профиль
                </a>
            </li>
            {% if user.is_superuser %}
                <li><a href="{% url 'admin_staff:users' %}"
                       class="dropdown-item {% if request.resolver_match.view_name == 'basket:view' %}
                active {% endif %}">Admin</a></li>
                <li><a href="{% url 'ordersapp:main' %}"
                       class="dropdown-item {% if request.resolver_match.view_name == 'basket:view' %}
                active {% endif %}">Заказы</a></li>
            {% endif %}
            {% if basket %}
                <li><a href="{% url 'basket:view' %}"
                       class="dropdown-item {% if request.resolver_match.view_name == 'basket:view' %}
                active {% endif %}">Корзина</a></li>
            {% endif %}

            <li>
                {% if user.is_authenticated %}
                    <a href="{% url 'auth:logout' %}">выйти</a>
                {% endif %}
            </li>

        </ul>
    {% endif %}



    {% if basket.0 %}
        <li>
        <span>
            {{ basket.0.total_cost|floatformat:0 }} руб.
            {{ basket.0.total_quantity }} шт.
        </span>
        </li>

    {% endif %}
    <li>
        {% if not user.is_active %}
            <a href="{% url 'auth:login' %}">войти</a>
            </li>
        {% endif %}
</ul>

lesson_1/geekshop/geekshop/templates/geekshop/includes/slider.html
<div class="slider">
			<div class="header clearfix">
				<a href="/" class="logo"></a>
                    {% include "geekshop/includes/menu.html" %}
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="/static/geekshop/img/arrow.png" alt=""></a>
			</div>
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>